
package payphone.easypay.core.ws;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentService", targetNamespace = "http://ws.core.payphone/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentService {


    /**
     * 
     * @param paymentId
     * @param lastEventId
     * @return
     *     returns payphone.easypay.core.ws.PaymentEventsBlock
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPaymentEvents", targetNamespace = "http://ws.core.payphone/", className = "payphone.easypay.core.ws.GetPaymentEvents")
    @ResponseWrapper(localName = "getPaymentEventsResponse", targetNamespace = "http://ws.core.payphone/", className = "payphone.easypay.core.ws.GetPaymentEventsResponse")
    public PaymentEventsBlock getPaymentEvents(
        @WebParam(name = "paymentId", targetNamespace = "")
        String paymentId,
        @WebParam(name = "lastEventId", targetNamespace = "")
        Long lastEventId);

    /**
     * 
     * @return
     *     returns java.util.List<payphone.easypay.core.ws.PaymentMethod>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPaymentMethods", targetNamespace = "http://ws.core.payphone/", className = "payphone.easypay.core.ws.GetPaymentMethods")
    @ResponseWrapper(localName = "getPaymentMethodsResponse", targetNamespace = "http://ws.core.payphone/", className = "payphone.easypay.core.ws.GetPaymentMethodsResponse")
    public List<PaymentMethod> getPaymentMethods();

    /**
     * 
     * @param amount
     * @param paymentMethodId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "beginPayment", targetNamespace = "http://ws.core.payphone/", className = "payphone.easypay.core.ws.BeginPayment")
    @ResponseWrapper(localName = "beginPaymentResponse", targetNamespace = "http://ws.core.payphone/", className = "payphone.easypay.core.ws.BeginPaymentResponse")
    public String beginPayment(
        @WebParam(name = "paymentMethodId", targetNamespace = "")
        String paymentMethodId,
        @WebParam(name = "amount", targetNamespace = "")
        BigDecimal amount);

}
