
package payphone.easypay.core.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentService", targetNamespace = "http://ws.core.payphone/", wsdlLocation = "http://167.205.35.211:8080/easypay/PaymentService?wsdl")
public class PaymentService_Service
    extends Service
{

    private final static URL PAYMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTSERVICE_EXCEPTION;
    private final static QName PAYMENTSERVICE_QNAME = new QName("http://ws.core.payphone/", "PaymentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://167.205.35.211:8080/easypay/PaymentService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTSERVICE_WSDL_LOCATION = url;
        PAYMENTSERVICE_EXCEPTION = e;
    }

    public PaymentService_Service() {
        super(__getWsdlLocation(), PAYMENTSERVICE_QNAME);
    }

    public PaymentService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTSERVICE_QNAME, features);
    }

    public PaymentService_Service(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTSERVICE_QNAME);
    }

    public PaymentService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTSERVICE_QNAME, features);
    }

    public PaymentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentService
     */
    @WebEndpoint(name = "payment")
    public PaymentService getPayment() {
        return super.getPort(new QName("http://ws.core.payphone/", "payment"), PaymentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentService
     */
    @WebEndpoint(name = "payment")
    public PaymentService getPayment(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.core.payphone/", "payment"), PaymentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTSERVICE_EXCEPTION!= null) {
            throw PAYMENTSERVICE_EXCEPTION;
        }
        return PAYMENTSERVICE_WSDL_LOCATION;
    }

}
