# Generated by Django 2.1.3 on 2018-11-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
