# Generated by Django 2.1.3 on 2018-11-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20181112_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.IntegerField(null=True),
        ),
    ]
