# Generated by Django 2.1.3 on 2018-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.IntegerField(null=True),
        ),
    ]
