# Generated by Django 2.1.3 on 2018-11-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('identity_number', models.CharField(max_length=30)),
                ('mobile_phone', models.CharField(max_length=14)),
            ],
        ),
    ]
